{
    "name": "secretwebmaster/laravel-namesilo",
    "description": "Communicate with Namesilo API in your laravel project",
    "type": "library",
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "Secretwebmaster\\LaravelNamesilo\\": "src/"
        }
    },
    "authors": [
        {
            "name": "secretwebmaster",
            "email": "earnbyshare2016@gmail.com"
        }
    ],
    "require": {} 
}
